=== raml-apis/SmartSheet/schemas/getWorkspaceResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "sheets" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "accessLevel" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "accessLevel" : {
      "type" : "string" ,
      "required" : false
    } ,
    "id" : {
      "type" : "number" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "permalink" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/SmartSheet/examples/listAllWorkspacesResponse-example.json
[
  {
    "accessLevel" : "OWNER" ,
    "id" : 3457273486960516 ,
    "name" : "workspace 1" ,
    "permalink" : "https://www.smartsheet.com/b/home?lx=JNL0bgXtXc0pzni9tzAc4g"
  } , {
    "accessLevel" : "OWNER" ,
    "id" : 7960873114331012 ,
    "name" : "workspace 2" ,
    "permalink" : "https://www.smartsheet.com/b/home?lx=JLiJbgXtXc0pzni9tzAKiR"
  }
]
