=== raml-apis/SmartSheet/schemas/listAllContentsResponse-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "folders" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "sheets" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "accessLevel" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "number" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "templates" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
      ]
    } ,
    "workspaces" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
      ]
    }
  }
}

=== raml-apis/SmartSheet/examples/listAllContentsResponse-example.json
{
  "folders" : [
    {
      "id" : 5709073300645764 ,
      "name" : "folder 1"
    }
  ] ,
  "sheets" : [
    {
      "accessLevel" : "OWNER" ,
      "id" : 4583173393803140 ,
      "name" : "sheet 1"
    } , {
      "accessLevel" : "OWNER" ,
      "id" : 2331373580117892 ,
      "name" : "sheet 2"
    }
  ] ,
  "templates" : [
  ] ,
  "workspaces" : [
  ]
}
