=== raml-apis/SmartSheet/schemas/sharetoManyRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "users" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "email" : {
              "type" : "string" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "subject" : {
      "type" : "string" ,
      "required" : false
    } ,
    "message" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessLevel" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ccMe" : {
      "type" : "boolean" ,
      "required" : false
    }
  }
}

=== raml-apis/SmartSheet/examples/sharetoManyRequest-example.json
{
  "users" : [
    {
      "email" : "john.doe@smartsheet.com"
    } , {
      "email" : "jane.doe@smartsheet.com"
    }
  ] ,
  "subject" : "My new Smartsheet" ,
  "message" : "I have shared a Smartsheet with you. Please review it for the latest updates" ,
  "accessLevel" : "ADMIN" ,
  "ccMe" : false
}
