=== raml-apis/SmartSheet/schemas/sharewithGroupstoManyRequest-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "shares" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "userId" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } , {
          "type" : "object" ,
          "properties" : {
            "type" : {
              "type" : "string" ,
              "required" : false
            } ,
            "groupId" : {
              "type" : "number" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "subject" : {
      "type" : "string" ,
      "required" : false
    } ,
    "message" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accessLevel" : {
      "type" : "string" ,
      "required" : false
    } ,
    "ccMe" : {
      "type" : "boolean" ,
      "required" : false
    }
  }
}

=== raml-apis/SmartSheet/examples/sharewithGroupstoManyRequest-example.json
{
  "shares" : [
    {
      "type" : "USER" ,
      "userId" : 1539725208119172
    } , {
      "type" : "GROUP" ,
      "groupId" : 2331373580117892
    }
  ] ,
  "subject" : "My new Smartsheet" ,
  "message" : "I have shared a Smartsheet with you. Please review it for the latest updates" ,
  "accessLevel" : "ADMIN" ,
  "ccMe" : false
}
